# Generated by Django 5.2.9 on 2025-12-16 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="roll_no",
        ),
        migrations.AddField(
            model_name="student",
            name="attendance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_number",
            field=models.CharField(default="UNKNOWN", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="marks",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(max_length=50),
        ),
    ]
